Add py.typed marker file to support type checking
Even though all classes in the `disjoint_set` package come with type
annotations, projects which use `disjoint_set` installed from PyPI get
typing errors:

    $ python3 -m mypy --strict file.py
    file.py:5: error: Skipping analyzing 'disjoint_set': found module but no type hints or library stubs
    file.py:5: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports

According to PEP 561, a package which provides type hints must be marked
using a marker file named `py.typed` or otherwise it's considered not
typed. We add the missing file to the source and built distributions
which should fix the errors quoted above.